<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.lazyegg</groupId>
        <artifactId>lazyegg-framework-parent</artifactId>
        <version>1.0.3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>lazyegg-tenant</artifactId>
    <name>lazyegg-tenant</name>
    <description>tenant</description>
    <url>https://github.com/nsmeng3/lazyegg-framework/tree/main/lazyegg-tenant</url>
    <!-- 开发人员信息 -->
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <!-- <distribution>repo</distribution> -->
        </license>
    </licenses>
    <scm>
        <connection>scm:https://github.com/nsmeng3/lazyegg-framework.git</connection>
        <developerConnection>scm:https://github.com/nsmeng3/lazyegg-framework.git</developerConnection>
        <url>https://github.com/nsmeng3/lazyegg-framework.git</url>
    </scm>
    <developers>
        <developer>
            <name>DifferentW</name>
            <email>dev@lazyegg.io</email>
            <organization>https://github.com/nsmeng3</organization>
            <timezone>+8</timezone>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>io.lazyegg</groupId>
            <artifactId>lazyegg-database</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <includes>
                    <include>META-INF/*.*</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
