<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.lazyegg</groupId>
        <artifactId>lazyegg-framework-parent</artifactId>
        <version>1.0.4</version>
    </parent>

    <artifactId>lazyegg-auth</artifactId>
    <groupId>io.lazyegg</groupId>
    <version>1.0.4</version>
    <name>lazyegg-auth</name>
    <description>auth</description>
    <url>https://github.com/nsmeng3/lazyegg-framework/tree/main/lazyegg-auth</url>
    <!-- 开发人员信息 -->
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <connection>scm:https://github.com/nsmeng3/lazyegg-framework.git</connection>
        <developerConnection>scm:https://github.com/nsmeng3/lazyegg-framework.git</developerConnection>
        <url>https://github.com/nsmeng3/lazyegg-framework.git</url>
    </scm>
    <developers>
        <developer>
            <name>DifferentW</name>
            <email>dev@lazyegg.io</email>
            <organization>https://github.com/nsmeng3</organization>
            <timezone>+8</timezone>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>io.lazyegg</groupId>
            <artifactId>lazyegg-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>${jjwt.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>${jose-jwt.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <version>${spring-security.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>${fastjson.version}</version>
        </dependency>
    </dependencies>
    <build>
        <finalName>lazyegg-auth</finalName>
    </build>
</project>
