<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.lazyegg</groupId>
    <artifactId>lazyegg-bom</artifactId>
    <version>1.0.4</version>
    <packaging>pom</packaging>
    <name>lazyegg-bom</name>
    <description>lazyegg-bom</description>
    <url>https://github.com/nsmeng3/lazyegg-framework/tree/main/lazyegg-bom</url>
    <!-- 开发人员信息 -->
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <!-- <distribution>repo</distribution> -->
        </license>
    </licenses>
    <scm>
        <connection>scm:https://github.com/nsmeng3/lazyegg-framework.git</connection>
        <developerConnection>scm:https://github.com/nsmeng3/lazyegg-framework.git</developerConnection>
        <url>https://github.com/nsmeng3/lazyegg-framework.git</url>
    </scm>
    <developers>
        <developer>
            <name>DifferentW</name>
            <email>dev@lazyegg.io</email>
            <organizationUrl>https://github.com/nsmeng3</organizationUrl>
        </developer>
    </developers>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-core</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-database</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-auth</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg.plugin</groupId>
                <artifactId>lazyegg-plugin-generator</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-swagger</artifactId>
                <version>1.0.4</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-tenant</artifactId>
                <version>1.0.4</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.8.0</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                    <autoPublish>false</autoPublish>
                    <waitUntil>validated</waitUntil>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.4</version>
                <configuration>
                    <show>private</show>
                    <nohelp>true</nohelp>
                    <charset>UTF-8</charset>
                    <encoding>UTF-8</encoding>
                    <docencoding>UTF-8</docencoding>
                    <!-- TODO 临时解决不规范的javadoc生成报错,后面要规范化后把这行去掉 -->
                    <additionalparam>-Xdoclint:none</additionalparam>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <testSource>${java.version}</testSource>
                    <testTarget>${java.version}</testTarget>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
