<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.lazyegg</groupId>
        <artifactId>lazyegg-sonatype</artifactId>
        <version>1.0.2</version>
        <relativePath/>
    </parent>

    <groupId>io.lazyegg</groupId>
    <artifactId>lazyegg-bom</artifactId>
    <version>1.0.2</version>
    <packaging>pom</packaging>
    <name>lazyegg-bom</name>
    <description>lazyegg-bom</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-core</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-database</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-auth</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg.plugin</groupId>
                <artifactId>lazyegg-plugin-generator</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-swagger</artifactId>
                <version>1.0.3</version>
            </dependency>
            <dependency>
                <groupId>io.lazyegg</groupId>
                <artifactId>lazyegg-tenant</artifactId>
                <version>1.0.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
