<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.lazyegg</groupId>
        <artifactId>lazyegg-framework-parent</artifactId>
        <version>1.0.4</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>lazyegg-plugin-generator</artifactId>
    <groupId>io.lazyegg</groupId>
    <version>1.0.4</version>
    <name>lazyegg-plugin-generator</name>
    <description>lazyegg-plugin-generator</description>
    <url>https://github.com/nsmeng3/lazyegg-framework/tree/main/lazyegg-plugin-generator</url>
    <!-- 开发人员信息 -->
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <!-- <distribution>repo</distribution> -->
        </license>
    </licenses>
    <scm>
        <connection>scm:https://github.com/nsmeng3/lazyegg-framework.git</connection>
        <developerConnection>scm:https://github.com/nsmeng3/lazyegg-framework.git</developerConnection>
        <url>https://github.com/nsmeng3/lazyegg-framework.git</url>
    </scm>
    <developers>
        <developer>
            <name>DifferentW</name>
            <email>dev@lazyegg.io</email>
            <organization>https://github.com/nsmeng3</organization>
            <timezone>+8</timezone>
        </developer>
    </developers>
    <properties>
        <skip.springboot.maven>false</skip.springboot.maven>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>${velocity-engine-core.version}</version>
        </dependency>
        <dependency>
            <groupId>io.lazyegg</groupId>
            <artifactId>lazyegg-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
